# Generated by Django 4.2.6 on 2023-11-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StocksApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskResult',
        ),
    ]
