# Generated by Django 4.2.6 on 2023-11-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userprofile_investment_userprofile_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='investment',
            field=models.CharField(choices=[('RP', 'Retirement Planning'), ('CI', 'Counter Inflation'), ('SI', 'Side Income')], default='RP', max_length=2, null=True),
        ),
    ]
