# Generated by Django 4.2.6 on 2023-11-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_alter_userprofile_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='investment',
            field=models.CharField(choices=[('RP', 'Retirement Planning'), ('CI', 'Counter Inflation'), ('SI', 'Side Income')], max_length=2, null=True),
        ),
    ]
