# Generated by Django 4.2.6 on 2023-11-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_userprofile_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_password_reset_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
